export const CRICKETER_LIST_REQUEST = "CRICKETER_LIST_REQUEST";
export const CRICKETER_LIST_SUCCESS = "CRICKETER_LIST_SUCCESS";
export const CRICKETER_LIST_FAIL = "CRICKETER_LIST_FAIL";

export const CRICKETER_DETAILS_REQUEST = "CRICKETER_DETAILS_REQUEST";
export const CRICKETER_DETAILS_SUCCESS = "CRICKETER_DETAILS_SUCCESS";
export const CRICKETER_DETAILS_FAIL = "CRICKETER_DETAILS_FAIL";

export const CRICKETER_DELETE_REQUEST = "CRICKETER_DELETE_REQUEST";
export const CRICKETER_DELETE_SUCCESS = "CRICKETER_DELETE_SUCCESS";
export const CRICKETER_DELETE_FAIL = "CRICKETER_DELETE_FAIL";

export const CRICKETER_CREATE_REQUEST = "CRICKETER_CREATE_REQUEST";
export const CRICKETER_CREATE_SUCCESS = "CRICKETER_CREATE_SUCCESS";
export const CRICKETER_CREATE_FAIL = "CRICKETER_CREATE_FAIL";
export const CRICKETER_CREATE_RESET = "CRICKETER_CREATE_RESET";

export const CRICKETER_UPDATE_REQUEST = "CRICKETER_UPDATE_REQUEST";
export const CRICKETER_UPDATE_SUCCESS = "CRICKETER_UPDATE_SUCCESS";
export const CRICKETER_UPDATE_FAIL = "CRICKETER_UPDATE_FAIL";
export const CRICKETER_UPDATE_RESET = "CRICKETER_UPDATE_RESET";
